import type { Metadata } from "next";
import "@/app/_assets/styles/globals.css";
import AppFooter from "@/app/_components/layout/AppFooter";
import AppNavbar from "@/app/_components/layout/AppNavBar";
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/sonner";
import MySessionProvider from "./_components/MySessionProvider/MySessionProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html dir="ltr" lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.1/css/all.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@mdi/font@7.4.47/css/materialdesignicons.min.css"
        />
      </head>

      <body>
        <StoreProvider>
          <MySessionProvider>
            <AppNavbar />
            {children}
            <Toaster />
            <AppFooter />
          </MySessionProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
